(function(){
  'use strict';
  const MAX_FILE_SIZE=10*1024*1024;
  const state={file:null,analysis:null,compareFiles:{a:null,b:null},comparison:null};
  const codePattern=/ELA\.\d+\.[A-Z]+\.\d+\.\d+/i;
  const standardMap=new Map((window.FL_BEST_STANDARDS||[]).map(s=>[String(s.code).toUpperCase(),s.description]));

  function norm(value){return String(value??'').trim()}
  function normHead(value){return norm(value).toLowerCase().replace(/[^a-z0-9]+/g,' ' ).trim()}
  function findHeader(headers,patterns){return headers.findIndex(h=>patterns.some(p=>p.test(normHead(h))))}
  function benchmarkCode(value){const match=norm(value).toUpperCase().match(codePattern);return match?match[0]:''}
  function resultValue(value){
    if(value===1||value===true)return'correct';
    if(value===0||value===false)return'incorrect';
    const s=norm(value).toLowerCase();
    if(!s)return'';
    if(['incorrect','wrong','i','no','n','false','fail','failed','0','x'].includes(s))return'incorrect';
    if(['correct','c','yes','y','true','pass','passed','1'].includes(s))return'correct';
    return'';
  }
  function statusValue(value){const s=norm(value).toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ');if(['above','above standard','above the standard','above benchmark'].includes(s))return'above';if(['at','at standard','at the standard','at/near the standard','at near the standard','at benchmark','on standard'].includes(s))return'at';if(['below','below standard','below the standard','below benchmark'].includes(s))return'below';return''}
  function pmValue(value){const s=norm(value);if(!s)return'';const match=s.match(/(?:level\s*)?([1-5])(?:\.0)?$/i);return match?Number(match[1]):''}
  function categoryFor(code){if(/\.R\.1\./.test(code))return'Reading Prose & Poetry';if(/\.R\.2\./.test(code))return'Reading Informational Text';return'Reading Across Genres & Vocabulary'}
  function studentRecord(code,name=''){return{code,name,ell:'',pm:'',pm1:'',pm2:'',pm3:'',items:{},questions:{},questionBenchmarks:{},statuses:{},categoryPerformance:{}}}

  function parseMatrix(matrix,filename){
    const rows=matrix.filter(row=>Array.isArray(row)&&row.some(cell=>norm(cell)));
    if(rows.length<2)throw new Error('The first worksheet needs a header row and at least one data row.');
    const headers=rows[0].map(norm),data=rows.slice(1);
    const codeIndex=findHeader(headers,[/^student id$/,/^studentid$/]);
    const nameIndex=findHeader(headers,[/^student name$/,/^full name$/,/^name$/]);
    if(codeIndex<0||nameIndex<0){const missing=[];if(nameIndex<0)missing.push('Student Name');if(codeIndex<0)missing.push('Student ID');throw new Error(`Required column${missing.length===1?'':'s'} missing: ${missing.join(' and ')}.`)}
    const benchmarkIndex=findHeader(headers,[/^benchmark( code)?$/,/^substandard( code)?$/,/^standard( code)?$/]);
    const questionIndex=findHeader(headers,[/^question( number| id)?$/,/^item( number| id)?$/]);
    const resultIndex=findHeader(headers,[/^result$/,/^status$/,/^correct incorrect$/,/^correct$/,/^item result$/]);
    const pmIndexes={pm:findHeader(headers,[/^pm( level)?$/,/^achievement level$/,/fast ela reading achievement level$/]),pm1:findHeader(headers,[/^pm ?1( level)?$/]),pm2:findHeader(headers,[/^pm ?2( level)?$/]),pm3:findHeader(headers,[/^pm ?3( level)?$/])};
    const ellIndex=findHeader(headers,[/^english language learner ell status$/,/^ell status$/,/^ell$/]);
    const students=new Map(),benchmarks=new Set(),questions=new Map();
    const getStudent=(code,name='')=>{if(!students.has(code))students.set(code,studentRecord(code,name));const student=students.get(code);if(name&&!student.name)student.name=name;return student};
    const addCommon=(student,row)=>{Object.entries(pmIndexes).forEach(([key,index])=>{if(index>=0&&pmValue(row[index])!=='')student[key]=pmValue(row[index])});if(ellIndex>=0){const value=norm(row[ellIndex]).toLowerCase();student.ell=value==='yes'||value==='y'||value==='true'||value==='1'?'yes':value?'no':''}};
    const fastSlots=headers.map((header,index)=>{const match=normHead(header).match(/^(\d+) benchmark$/);if(!match)return null;const n=Number(match[1]);return{n,benchmark:index,earned:findHeader(headers,[new RegExp(`^${n} points earned$`)]),possible:findHeader(headers,[new RegExp(`^${n} points possible$`)])}}).filter(slot=>slot&&slot.earned>=0&&slot.possible>=0);
    const categoryColumns=[['prose','Reading Prose & Poetry',findHeader(headers,[/reading prose and poetry performance$/])],['info','Reading Informational Text',findHeader(headers,[/reading informational text performance$/])],['across','Reading Across Genres & Vocabulary',findHeader(headers,[/reading across genres vocabulary performance$/])]];
    let format='wide',unreadable=0,duplicates=0,specialized=false;
    if(fastSlots.length){
      format='fast-pm-export';specialized=true;
      data.forEach(row=>{const code=norm(row[codeIndex]),name=norm(row[nameIndex]);if(!code)return;const student=getStudent(code,name);addCommon(student,row);categoryColumns.forEach(([key,,index])=>{if(index>=0&&statusValue(row[index]))student.categoryPerformance[key]=statusValue(row[index])});fastSlots.forEach(slot=>{const benchmark=benchmarkCode(row[slot.benchmark]),earned=Number(row[slot.earned]),possible=Number(row[slot.possible]);if(!benchmark||!Number.isFinite(earned)||!Number.isFinite(possible)||possible<=0)return;const id=`Question ${slot.n}`,result=earned>=possible?'correct':'incorrect';benchmarks.add(benchmark);if(!questions.has(id))questions.set(id,{label:id,codes:new Set()});questions.get(id).codes.add(benchmark);student.questions[id]=result;student.questionBenchmarks[id]=benchmark})});
    }else if(benchmarkIndex>=0&&resultIndex>=0){
      format='long';
      data.forEach(row=>{const code=norm(row[codeIndex]),name=norm(row[nameIndex]);if(!code)return;const student=getStudent(code,name),benchmark=benchmarkCode(row[benchmarkIndex]),result=resultValue(row[resultIndex]),status=statusValue(row[resultIndex]);addCommon(student,row);if(!benchmark){if(norm(row[benchmarkIndex]))unreadable++;return}benchmarks.add(benchmark);if(status){if(student.statuses[benchmark])duplicates++;student.statuses[benchmark]=status;return}const question=questionIndex>=0&&norm(row[questionIndex])?norm(row[questionIndex]):benchmark;questions.set(question,{label:question,code:benchmark});if(result){if(student.questions[question])duplicates++;student.questions[question]=result}});
    }else{
      const benchmarkColumns=headers.map((header,index)=>{const values=data.map(row=>row[index]).filter(v=>norm(v));const kind=values.some(v=>statusValue(v))?'status':'question';return{index,code:benchmarkCode(header),question:norm(header)||`Question ${index+1}`,kind}}).filter(x=>x.code);
      if(!benchmarkColumns.length)throw new Error('No benchmark columns were found. Use headings such as ELA.8.R.1.1, or use the Long layout.');
      benchmarkColumns.forEach(x=>{benchmarks.add(x.code);if(x.kind==='question'){let id=x.question;if(questions.has(id))id=`${id} [column ${x.index+1}]`;x.id=id;questions.set(id,{label:x.question,code:x.code})}});
      data.forEach(row=>{const code=norm(row[codeIndex]),name=norm(row[nameIndex]);if(!code)return;const student=getStudent(code,name);addCommon(student,row);benchmarkColumns.forEach(({index,id,code:benchmark,kind})=>{if(kind==='status'){const status=statusValue(row[index]);if(status)student.statuses[benchmark]=status;else if(norm(row[index]))unreadable++}else{const result=resultValue(row[index]);if(result)student.questions[id]=result;else if(norm(row[index]))unreadable++}})});
    }
    const studentList=[...students.values()];
    if(!studentList.length)throw new Error('No rows with student IDs were found.');
    const classSize=studentList.length;
    studentList.forEach(student=>{benchmarks.forEach(code=>{const results=[...questions].filter(([id,q])=>specialized?student.questionBenchmarks[id]===code:q.code===code).map(([id])=>student.questions[id]).filter(Boolean);if(results.includes('incorrect'))student.items[code]='incorrect';else if(results.includes('correct'))student.items[code]='correct'})});
    const benchmarkList=[...benchmarks].sort().map(code=>{const correct=studentList.filter(s=>s.items[code]==='correct').length,incorrect=studentList.filter(s=>s.items[code]==='incorrect').length,above=studentList.filter(s=>s.statuses[code]==='above').length,at=studentList.filter(s=>s.statuses[code]==='at').length,below=studentList.filter(s=>s.statuses[code]==='below').length,hasStatus=above+at+below>0,assessed=hasStatus?above+at+below:correct+incorrect,missing=classSize-assessed,missed=hasStatus?below:incorrect,denominator=specialized?assessed:classSize;return{code,description:standardMap.get(code)||'',category:categoryFor(code),correct,incorrect,above,at,below,hasStatus,missing,attempted:assessed,denominator,pctMissed:denominator?missed/denominator:0,missedStudents:studentList.filter(s=>hasStatus?s.statuses[code]==='below':s.items[code]==='incorrect').map(s=>s.name?`${s.name} (${s.code})`:s.code)}});
    const questionList=[...questions].map(([id,q])=>{const correct=studentList.filter(s=>s.questions[id]==='correct').length,incorrect=studentList.filter(s=>s.questions[id]==='incorrect').length,missing=classSize-correct-incorrect,denominator=specialized?correct+incorrect:classSize,codes=q.codes?[...q.codes].sort():[q.code],code=codes.join(', '),description=codes.map(c=>`${c} — ${standardMap.get(c)||'Definition unavailable'}`).join('; ');return{id,label:q.label,code,codes,description,correct,incorrect,missing,denominator,pctCorrect:denominator?correct/denominator:0,pctMissed:denominator?incorrect/denominator:0}});
    const categorySummary=categoryColumns.filter(([,label,index])=>index>=0).map(([key,label])=>{const above=studentList.filter(s=>s.categoryPerformance[key]==='above').length,at=studentList.filter(s=>s.categoryPerformance[key]==='at').length,below=studentList.filter(s=>s.categoryPerformance[key]==='below').length;return{key,label,above,at,below,entered:above+at+below}});
    const ellReported=studentList.filter(s=>s.ell),ellStudents=studentList.filter(s=>s.ell==='yes'),nonEllStudents=studentList.filter(s=>s.ell==='no');
    const ellGroup=(label,list)=>({label,count:list.length,levels:[1,2,3,4,5].map(level=>({level,count:list.filter(s=>s.pm===level).length,pct:list.length?list.filter(s=>s.pm===level).length/list.length:0})),categories:categoryColumns.filter(([,name,index])=>index>=0).map(([key,name])=>{const entered=list.filter(s=>s.categoryPerformance[key]),above=list.filter(s=>s.categoryPerformance[key]==='above').length,at=list.filter(s=>s.categoryPerformance[key]==='at').length,below=list.filter(s=>s.categoryPerformance[key]==='below').length;return{key,name,entered:entered.length,above,at,below}}),standards:benchmarkList.map(b=>{const assessed=list.filter(s=>s.items[b.code]),missed=assessed.filter(s=>s.items[b.code]==='incorrect').length;return{code:b.code,assessed:assessed.length,missed,pctMissed:assessed.length?missed/assessed.length:0}}),questions:questionList.map(q=>{const assessed=list.filter(s=>s.questions[q.id]),missed=assessed.filter(s=>s.questions[q.id]==='incorrect').length;return{id:q.id,assessed:assessed.length,missed,pctMissed:assessed.length?missed/assessed.length:0}})});
    const ellSummary={available:ellReported.length>0,reported:ellReported.length,ellCount:ellStudents.length,nonEllCount:nonEllStudents.length,ellPercent:ellReported.length?ellStudents.length/ellReported.length:0,ell:ellGroup('ELL',ellStudents),nonEll:ellGroup('Non-ELL',nonEllStudents)};
    return{filename,format,students:studentList,benchmarks:benchmarkList,questions:questionList,categorySummary,ellSummary,denominatorMode:specialized?'assessed':'class',benchmarksSource:fastSlots.length?'FAST numbered question blocks':'benchmark columns',priority:benchmarkList.filter(b=>b.pctMissed>=.45),questionPriority:questionList.filter(q=>q.pctMissed>=.45),unreadable,duplicates};
  }

  async function readUpload(file){
    if(!window.XLSX)throw new Error('Spreadsheet reader did not load. Refresh the page and try again.');
    if(file.size>MAX_FILE_SIZE)throw new Error('This file is larger than 10 MB. Remove unused worksheets or columns and try again.');
    const bytes=await file.arrayBuffer(),workbook=XLSX.read(bytes,{type:'array',cellDates:false});
    if(!workbook.SheetNames.length)throw new Error('The workbook does not contain a worksheet.');
    const sheet=workbook.Sheets[workbook.SheetNames[0]];
    return parseMatrix(XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:false}),file.name);
  }

  function setStatus(message,type=''){$('upload-status').className=`upload-status ${type}`.trim();$('upload-status').textContent=message}
  function escape(value){return htmlEscape(String(value??''))}
  function pct(value){return`${Math.round(value*100)}%`}
  function movementFor(students,a,b){const valid=students.filter(s=>Number.isFinite(s[a])&&Number.isFinite(s[b]));return{valid:valid.length,up:valid.filter(s=>s[b]>s[a]).length,same:valid.filter(s=>s[b]===s[a]).length,down:valid.filter(s=>s[b]<s[a]).length}}

  function renderAnalysis(analysis){
    const classSize=analysis.students.length,m12=movementFor(analysis.students,'pm1','pm2'),m23=movementFor(analysis.students,'pm2','pm3'),m13=movementFor(analysis.students,'pm1','pm3');
    const movement=m12.valid||m23.valid||m13.valid?`<div class="stats"><div class="stat"><b>${m12.valid?pct(m12.up/m12.valid):'—'}</b>moved up PM1→PM2</div><div class="stat"><b>${m23.valid?pct(m23.up/m23.valid):'—'}</b>moved up PM2→PM3</div><div class="stat"><b>${m13.valid?pct(m13.up/m13.valid):'—'}</b>moved up PM1→PM3</div></div>`:'';
    const levelRows=['pm','pm1','pm2','pm3'].map(key=>{const valid=analysis.students.filter(s=>Number.isFinite(s[key]));if(!valid.length)return'';return`<tr><td>${key==='pm'?'Uploaded PM':key.toUpperCase()}</td>${[1,2,3,4,5].map(level=>`<td>${pct(valid.filter(s=>s[key]===level).length/valid.length)}</td>`).join('')}<td>${valid.length}</td></tr>`}).filter(Boolean).join('');
    const levels=levelRows?`<h4>Reported achievement-level distribution</h4><div class="analysis-scroll"><table class="upload-results-table"><thead><tr><th>Window</th><th>Level 1</th><th>Level 2</th><th>Level 3</th><th>Level 4</th><th>Level 5</th><th>Students reported</th></tr></thead><tbody>${levelRows}</tbody></table></div>`:'';
    const categoryRows=(analysis.categorySummary||[]).filter(c=>c.entered).map(c=>`<tr><td><strong>${escape(c.label)}</strong></td><td>${pct(c.above/c.entered)}</td><td>${pct(c.at/c.entered)}</td><td>${pct(c.below/c.entered)}</td><td>${c.entered}</td></tr>`).join('');
    const categories=categoryRows?`<h4>FAST reporting-category performance</h4><div class="analysis-scroll"><table class="upload-results-table"><thead><tr><th>Reporting category</th><th>% above</th><th>% at/near</th><th>% below</th><th>Students reported</th></tr></thead><tbody>${categoryRows}</tbody></table></div>`:'';
    const e=analysis.ellSummary,ellLevels=e?.available?[1,2,3,4,5].map(level=>`<tr><td>Level ${level}</td><td>${pct(e.ell.levels[level-1].pct)}</td><td>${pct(e.nonEll.levels[level-1].pct)}</td></tr>`).join(''):'',ellCategories=e?.available?e.ell.categories.map((c,i)=>{const n=e.nonEll.categories[i],rate=(x,k)=>x.entered?pct(x[k]/x.entered):'—';return`<tr><td><strong>${escape(c.name)}</strong></td><td>${rate(c,'above')}</td><td>${rate(c,'at')}</td><td>${rate(c,'below')}</td><td>${rate(n,'above')}</td><td>${rate(n,'at')}</td><td>${rate(n,'below')}</td></tr>`}).join(''):'';
    const ellSection=e?.available?`<h4>ELL quantitative summary — aggregate only</h4><div class="stats"><div class="stat"><b>${e.ellCount}</b>ELL students</div><div class="stat"><b>${pct(e.ellPercent)}</b>of students with ELL status</div><div class="stat"><b>${e.nonEllCount}</b>non-ELL students</div></div><p class="hint">This comparison is class-level only. Individual students are not labeled ELL in the analysis or downloads.</p><div class="analysis-scroll"><table class="upload-results-table"><thead><tr><th>Achievement level</th><th>ELL</th><th>Non-ELL</th></tr></thead><tbody>${ellLevels}</tbody></table></div>${ellCategories?`<div class="analysis-scroll" style="margin-top:.65rem"><table class="upload-results-table"><thead><tr><th>Reporting category</th><th>ELL above</th><th>ELL at/near</th><th>ELL below</th><th>Non-ELL above</th><th>Non-ELL at/near</th><th>Non-ELL below</th></tr></thead><tbody>${ellCategories}</tbody></table></div>`:''}`:'';
    const benchmarkRows=analysis.benchmarks.map(b=>`<tr class="${b.pctMissed>=.45?'priority-row':''}"><td><strong>${escape(b.code)}</strong><br><span class="hint">${escape(b.description||'Description not found in the site catalog')}</span></td><td>${b.hasStatus?pct(b.above/classSize):'—'}</td><td>${b.hasStatus?pct(b.at/classSize):'—'}</td><td>${b.hasStatus?pct(b.below/classSize):'—'}</td><td>${pct(b.pctMissed)}</td><td>${pct(b.missing/classSize)}</td><td>${b.pctMissed>=.45?'<strong>45%+ priority</strong>':'—'}</td></tr>`).join('');
    const questionRows=analysis.questions.map(q=>`<tr class="${q.pctMissed>=.45?'priority-row':''}"><td><strong>${escape(q.label)}</strong></td><td>${escape(q.code)}<br><span class="hint"><strong>Standard meaning:</strong> ${escape(q.description||'Description not found in the site catalog')}</span></td><td>${pct(q.pctCorrect)}</td><td>${pct(q.pctMissed)}</td><td>${q.denominator}</td><td>${q.pctMissed>=.45?'<strong>45%+ priority</strong>':'—'}</td></tr>`).join('');
    const studentRows=analysis.students.map(s=>{const correct=Object.entries(s.items).filter(([,v])=>v==='correct').map(([c])=>c),missed=Object.entries(s.items).filter(([,v])=>v==='incorrect').map(([c])=>c);return`<tr><td><strong>${escape(s.name||'')}</strong></td><td>${escape(s.code)}</td><td>${correct.length}</td><td>${missed.length}</td><td>${escape(missed.join(', ')||'None recorded')}</td></tr>`}).join('');
    const groups=analysis.priority.length?analysis.priority.map(b=>`<div class="group urgent"><strong>${escape(b.code)} — ${pct(b.pctMissed)} of assessed students missed</strong>${escape(b.missedStudents.join(', '))}</div>`).join(''):'<div class="group ready"><strong>No 45%+ standard pattern</strong>No standard was missed by 45% or more of the assessed students.</div>';
    const denominatorNote=analysis.denominatorMode==='assessed'?'Question and standard percentages use only students who were assessed on that question or standard.':'Percent missed uses the full uploaded class as the denominator.';
    $('analysis-box').innerHTML=`<h3 style="margin-top:0">Uploaded FAST PM snapshot</h3><div class="stats"><div class="stat"><b>${classSize}</b>students</div><div class="stat"><b>${analysis.benchmarks.length}</b>standards found</div><div class="stat"><b>${analysis.questionPriority.length}</b>questions at 45%+</div></div>${levels}${categories}${ellSection}${movement}<h4>Standard performance and written definitions</h4><div class="analysis-scroll"><table class="upload-results-table"><thead><tr><th>Standard and written definition</th><th>% above</th><th>% at</th><th>% below</th><th>% missed</th><th>Not assessed</th><th>Flag</th></tr></thead><tbody>${benchmarkRows}</tbody></table></div><h4>Question analysis and standards touched</h4><div class="analysis-scroll"><table class="upload-results-table"><thead><tr><th>Question</th><th>Standard touched and written definition</th><th>% correct</th><th>% missed</th><th>Students assessed</th><th>Flag</th></tr></thead><tbody>${questionRows}</tbody></table></div><h4>Priority groups</h4><div class="groups">${groups}</div><h4>Individual student breakdown</h4><div class="analysis-scroll"><table class="upload-results-table"><thead><tr><th>Student Name</th><th>Student ID</th><th>Standards correct</th><th>Standards missed</th><th>Missed standards</th></tr></thead><tbody>${studentRows}</tbody></table></div><p class="hint">${denominatorNote} Achievement levels and reporting-category results come directly from the FAST file. ELL status is used only for the class-level summary. Section 504 data is ignored. Verify results against the source report.</p>`;
  }

  function prepareUploadExport(analysis){
    invalidateSpreadsheet();resetPdf();state.comparison=null;state.analysis=analysis;$('spreadsheet-export').hidden=false;$('spreadsheet-note').textContent=`Analysis completed for ${analysis.students.length} students. Create either report below.`;$('spreadsheet-sheets').textContent='Excel includes ELL Aggregate Summary, Student Results, Reporting Categories, Question Detail, Standard Summary, Question Summary, and 45%+ Questions. PDF begins with a whole-class narrative and then breaks down each student by name and ID.';
  }
  function styleSheet(ws,widths,filter){ws['!cols']=widths.map(w=>({wch:w}));if(filter)ws['!autofilter']={ref:filter}}
  function startDownload(link){link.hidden=false;try{link.click()}catch(error){link.hidden=false}}
  function buildUploadWorkbook(analysis){
    const studentHeader=['Student Name','Student ID','PM Level','PM1 Level','PM2 Level','PM3 Level','Prose & Poetry Performance','Informational Text Performance','Across Genres & Vocabulary Performance','Questions Correct','Questions Missed'];
    const studentData=analysis.students.map(s=>[s.name||'',s.code,s.pm,s.pm1,s.pm2,s.pm3,s.categoryPerformance.prose||'',s.categoryPerformance.info||'',s.categoryPerformance.across||'',Object.values(s.questions).filter(v=>v==='correct').length,Object.values(s.questions).filter(v=>v==='incorrect').length]);
    const detailHeader=['Student Name','Student ID','Question','Standard Code','Written Standard Definition','Question Result'];
    const detailData=analysis.students.flatMap(s=>analysis.questions.filter(q=>s.questions[q.id]).map(q=>{const code=s.questionBenchmarks[q.id]||q.code,description=standardMap.get(code)||q.description;return[s.name||'',s.code,q.label,code,description,s.questions[q.id]]}));
    const categoryHeader=['Reporting Category','Above','At / Near','Below','Students Reported','Percent Above','Percent At / Near','Percent Below'];
    const categoryData=(analysis.categorySummary||[]).filter(c=>c.entered).map(c=>[c.label,c.above,c.at,c.below,c.entered,c.above/c.entered,c.at/c.entered,c.below/c.entered]);
    const summaryHeader=['Reporting Category','Standard Code','Written Standard Definition','Above','At','Below','Not Assessed','Students Assessed','Percent Above','Percent At','Percent Missed','45%+ Priority'];
    const summaryData=analysis.benchmarks.map(b=>[b.category,b.code,b.description,b.hasStatus?b.above:'',b.hasStatus?b.at:'',b.hasStatus?b.below:'',b.missing,b.denominator,b.hasStatus?b.above/b.denominator:'',b.hasStatus?b.at/b.denominator:'',b.pctMissed,b.pctMissed>=.45?'Yes':'No']);
    const questionHeader=['Question','Standard Code','Written Standard Definition','Correct','Missed','Students Assessed','Percent Correct','Percent Missed','45%+ Priority'];
    const questionData=analysis.questions.map(q=>[q.label,q.code,q.description,q.correct,q.incorrect,q.denominator,q.pctCorrect,q.pctMissed,q.pctMissed>=.45?'Yes':'No']);
    const priorityData=analysis.questionPriority.map(q=>[q.label,q.code,q.description,q.correct,q.incorrect,q.denominator,q.pctCorrect,q.pctMissed,'Yes']);
    const e=analysis.ellSummary,ellRows=e?.available?[['ELL Aggregate Summary'],['Students with ELL status reported',e.reported],['ELL students',e.ellCount],['Non-ELL students',e.nonEllCount],['Percent ELL',e.ellPercent],[],['Achievement Level','ELL Count','ELL Percent','Non-ELL Count','Non-ELL Percent'],...[1,2,3,4,5].map(level=>[`Level ${level}`,e.ell.levels[level-1].count,e.ell.levels[level-1].pct,e.nonEll.levels[level-1].count,e.nonEll.levels[level-1].pct]),[],['Reporting Category','ELL Above','ELL At/Near','ELL Below','Non-ELL Above','Non-ELL At/Near','Non-ELL Below'],...e.ell.categories.map((c,i)=>[c.name,c.entered?c.above/c.entered:'',c.entered?c.at/c.entered:'',c.entered?c.below/c.entered:'',e.nonEll.categories[i].entered?e.nonEll.categories[i].above/e.nonEll.categories[i].entered:'',e.nonEll.categories[i].entered?e.nonEll.categories[i].at/e.nonEll.categories[i].entered:'',e.nonEll.categories[i].entered?e.nonEll.categories[i].below/e.nonEll.categories[i].entered:'']),[],['Privacy note','ELL is reported only in aggregate. No student row contains an individual ELL label. Section 504 data is not used.']]:[['ELL Aggregate Summary'],['No ELL status column was detected.']];
    const wb=XLSX.utils.book_new(),ellWs=XLSX.utils.aoa_to_sheet(ellRows),studentWs=XLSX.utils.aoa_to_sheet([studentHeader,...studentData]),categoryWs=XLSX.utils.aoa_to_sheet([categoryHeader,...categoryData]),detailWs=XLSX.utils.aoa_to_sheet([detailHeader,...detailData]),summaryWs=XLSX.utils.aoa_to_sheet([summaryHeader,...summaryData]),questionWs=XLSX.utils.aoa_to_sheet([questionHeader,...questionData]),priorityWs=XLSX.utils.aoa_to_sheet([questionHeader,...(priorityData.length?priorityData:[['No question reached the 45% threshold.']])]);
    styleSheet(studentWs,[28,18,11,11,11,11,26,28,34,18,18],`A1:K${studentData.length+1}`);styleSheet(categoryWs,[34,10,12,10,18,18,20,18],`A1:H${categoryData.length+1}`);styleSheet(detailWs,[28,18,18,20,62,18],`A1:F${detailData.length+1}`);styleSheet(summaryWs,[35,20,55,10,10,10,12,12,16,14,22,16],`A1:L${summaryData.length+1}`);styleSheet(questionWs,[18,20,62,10,10,18,18,18,16],`A1:I${questionData.length+1}`);styleSheet(priorityWs,[18,20,62,10,10,18,18,18,16],priorityData.length?`A1:I${priorityData.length+1}`:'');
    categoryData.forEach((_,i)=>['F','G','H'].forEach(col=>{const cell=categoryWs[`${col}${i+2}`];if(cell)cell.z='0.0%'}));summaryData.forEach((_,i)=>['I','J','K'].forEach(col=>{const cell=summaryWs[`${col}${i+2}`];if(cell)cell.z='0.0%'}));questionData.forEach((_,i)=>['G','H'].forEach(col=>{const cell=questionWs[`${col}${i+2}`];if(cell)cell.z='0.0%'}));priorityData.forEach((_,i)=>['G','H'].forEach(col=>{const cell=priorityWs[`${col}${i+2}`];if(cell)cell.z='0.0%'}));
    styleSheet(ellWs,[36,18,18,20,22,18,18],e?.available?`A7:E12`:'');if(e?.available){['B5','C8','E8','C9','E9','C10','E10','C11','E11','C12','E12'].forEach(ref=>{if(ellWs[ref])ellWs[ref].z='0.0%'})}
    XLSX.utils.book_append_sheet(wb,ellWs,'ELL Aggregate Summary');XLSX.utils.book_append_sheet(wb,studentWs,'Student Results');XLSX.utils.book_append_sheet(wb,categoryWs,'Reporting Categories');XLSX.utils.book_append_sheet(wb,detailWs,'Question Detail');XLSX.utils.book_append_sheet(wb,summaryWs,'Standard Summary');XLSX.utils.book_append_sheet(wb,questionWs,'Question Summary');XLSX.utils.book_append_sheet(wb,priorityWs,'45%+ Questions');
    const bytes=XLSX.write(wb,{bookType:'xlsx',type:'array'});if(spreadsheetUrl)URL.revokeObjectURL(spreadsheetUrl);spreadsheetUrl=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const link=$('download-spreadsheet'),date=new Date().toISOString().slice(0,10);link.href=spreadsheetUrl;link.download=`fast-pm-analysis-${date}.xlsx`;$('create-spreadsheet').hidden=true;$('spreadsheet-note').textContent=`Excel download started for ${analysis.students.length} students. If it did not start, use the Excel retry link below.`;startDownload(link);
  }

  function compareAnalyses(first,second,labelA,labelB){
    const aStudents=new Map(first.students.map(s=>[s.code,s])),bStudents=new Map(second.students.map(s=>[s.code,s])),matched=[...aStudents.keys()].filter(code=>bStudents.has(code));
    const byPosition=first.format==='fast-pm-export'&&second.format==='fast-pm-export',keyOf=q=>byPosition?q.label:`${q.code}|${q.label}`,aQuestions=new Map(first.questions.map(q=>[keyOf(q),q])),bQuestions=new Map(second.questions.map(q=>[keyOf(q),q])),questionMeta=new Map();[...first.questions,...second.questions].forEach(q=>{const key=keyOf(q),existing=questionMeta.get(key),codes=[...new Set([...(existing?.codes||[]),...(q.codes||[q.code])])].sort();questionMeta.set(key,{code:codes.join(', '),codes,label:q.label,description:codes.map(c=>`${c} — ${standardMap.get(c)||'Definition unavailable'}`).join('; ')})});
    const questionResults=[...questionMeta].map(([key,q])=>{const a=aQuestions.get(key),b=bQuestions.get(key),improved=[],regressed=[],stillMissed=[];matched.forEach(code=>{const av=aStudents.get(code).questions[a?.id],bv=bStudents.get(code).questions[b?.id];if(av==='incorrect'&&bv==='correct')improved.push(code);if(av==='correct'&&bv==='incorrect')regressed.push(code);if(av==='incorrect'&&bv==='incorrect')stillMissed.push(code)});return{...q,aMissed:a?a.pctMissed:null,bMissed:b?b.pctMissed:null,aCorrect:a?a.pctCorrect:null,bCorrect:b?b.pctCorrect:null,improved,regressed,stillMissed,priority:b&&b.pctMissed>=.45}});
    const standardCodes=[...new Set([...first.benchmarks,...second.benchmarks].map(b=>b.code))].sort();
    const standards=standardCodes.map(code=>{const a=first.benchmarks.find(b=>b.code===code),b=second.benchmarks.find(x=>x.code===code);return{code,description:b?.description||a?.description||'',a,b,priority:!!b&&b.pctMissed>=.45}});
    const students=matched.map(code=>{let improved=0,regressed=0,stillMissed=0;questionResults.forEach(q=>{if(q.improved.includes(code))improved++;if(q.regressed.includes(code))regressed++;if(q.stillMissed.includes(code))stillMissed++});const name=bStudents.get(code)?.name||aStudents.get(code)?.name||'';return{code,name,improved,regressed,stillMissed}});
    const categoryKeys=[...new Set([...(first.categorySummary||[]),...(second.categorySummary||[])].map(c=>c.key))],categories=categoryKeys.map(key=>({key,label:(first.categorySummary||[]).find(c=>c.key===key)?.label||(second.categorySummary||[]).find(c=>c.key===key)?.label||key,a:(first.categorySummary||[]).find(c=>c.key===key),b:(second.categorySummary||[]).find(c=>c.key===key)}));
    return{first,second,labelA,labelB,matched,onlyA:first.students.length-matched.length,onlyB:second.students.length-matched.length,questionResults,standards,categories,students,priority:questionResults.filter(q=>q.priority)};
  }

  function renderComparison(c){
    const dash=v=>v==null?'—':pct(v),questionRows=c.questionResults.map(q=>`<tr class="${q.priority?'priority-row':''}"><td><strong>${escape(q.label)}</strong></td><td>${escape(q.code)}<br><span class="hint">${escape(q.description)}</span></td><td>${dash(q.aMissed)}</td><td>${dash(q.bMissed)}</td><td>${q.improved.length}</td><td>${q.regressed.length}</td><td>${q.stillMissed.length}</td><td>${q.priority?'<strong>45%+ priority</strong>':'—'}</td></tr>`).join('');
    const standardRows=c.standards.map(s=>`<tr class="${s.priority?'priority-row':''}"><td><strong>${escape(s.code)}</strong><br><span class="hint">${escape(s.description)}</span></td><td>${s.a?.hasStatus?dash(s.a.above/c.first.students.length):'—'}</td><td>${s.a?.hasStatus?dash(s.a.at/c.first.students.length):'—'}</td><td>${s.a?dash(s.a.pctMissed):'—'}</td><td>${s.b?.hasStatus?dash(s.b.above/c.second.students.length):'—'}</td><td>${s.b?.hasStatus?dash(s.b.at/c.second.students.length):'—'}</td><td>${s.b?dash(s.b.pctMissed):'—'}</td></tr>`).join('');
    const studentRows=c.students.map(s=>`<tr><td><strong>${escape(s.name||'')}</strong></td><td>${escape(s.code)}</td><td>${s.improved}</td><td>${s.regressed}</td><td>${s.stillMissed}</td></tr>`).join('');
    const aLevel=c.first.students.filter(s=>Number.isFinite(s.pm)),bLevel=c.second.students.filter(s=>Number.isFinite(s.pm)),levelRows=[1,2,3,4,5].map(level=>`<tr><td>Level ${level}</td><td>${aLevel.length?pct(aLevel.filter(s=>s.pm===level).length/aLevel.length):'—'}</td><td>${bLevel.length?pct(bLevel.filter(s=>s.pm===level).length/bLevel.length):'—'}</td></tr>`).join(''),levels=aLevel.length||bLevel.length?`<h4>PM level comparison</h4><div class="analysis-scroll"><table class="upload-results-table"><thead><tr><th>Level</th><th>${escape(c.labelA)}</th><th>${escape(c.labelB)}</th></tr></thead><tbody>${levelRows}</tbody></table></div>`:'';
    const categoryRows=(c.categories||[]).filter(x=>x.a?.entered||x.b?.entered).map(x=>{const cell=(v,total)=>total?pct(v/total):'—';return`<tr><td><strong>${escape(x.label)}</strong></td><td>${cell(x.a?.above,x.a?.entered)}</td><td>${cell(x.a?.at,x.a?.entered)}</td><td>${cell(x.a?.below,x.a?.entered)}</td><td>${cell(x.b?.above,x.b?.entered)}</td><td>${cell(x.b?.at,x.b?.entered)}</td><td>${cell(x.b?.below,x.b?.entered)}</td></tr>`}).join(''),categories=categoryRows?`<h4>Reporting-category comparison</h4><div class="analysis-scroll"><table class="upload-results-table"><thead><tr><th>Category</th><th>${escape(c.labelA)} above</th><th>${escape(c.labelA)} at/near</th><th>${escape(c.labelA)} below</th><th>${escape(c.labelB)} above</th><th>${escape(c.labelB)} at/near</th><th>${escape(c.labelB)} below</th></tr></thead><tbody>${categoryRows}</tbody></table></div>`:'';
    const ellCompare=c.first.ellSummary?.available||c.second.ellSummary?.available?`<h4>ELL quantitative summary — aggregate only</h4><div class="analysis-scroll"><table class="upload-results-table"><thead><tr><th>Dataset</th><th>ELL students</th><th>Students with status</th><th>Percent ELL</th></tr></thead><tbody>${[[c.labelA,c.first.ellSummary],[c.labelB,c.second.ellSummary]].map(([label,e])=>`<tr><td><strong>${escape(label)}</strong></td><td>${e?.available?e.ellCount:'—'}</td><td>${e?.available?e.reported:'—'}</td><td>${e?.available?pct(e.ellPercent):'—'}</td></tr>`).join('')}</tbody></table></div><p class="hint">ELL results are shown only as class-level totals. Individual student ELL labels are never displayed or downloaded.</p>`:'';
    $('analysis-box').innerHTML=`<h3 style="margin-top:0">${escape(c.labelA)} → ${escape(c.labelB)} comparison</h3><div class="stats"><div class="stat"><b>${c.matched.length}</b>matched students</div><div class="stat"><b>${c.priority.length}</b>latest questions at 45%+</div><div class="stat"><b>${c.onlyA+c.onlyB}</b>unmatched records</div></div>${levels}${categories}${ellCompare}<h4>Standard performance comparison</h4><div class="analysis-scroll"><table class="upload-results-table"><thead><tr><th>Standard and written definition</th><th>${escape(c.labelA)} above</th><th>${escape(c.labelA)} at</th><th>${escape(c.labelA)} below/missed</th><th>${escape(c.labelB)} above</th><th>${escape(c.labelB)} at</th><th>${escape(c.labelB)} below/missed</th></tr></thead><tbody>${standardRows}</tbody></table></div><h4>Question/substandard comparison</h4><div class="analysis-scroll"><table class="upload-results-table"><thead><tr><th>Question</th><th>Standards touched and written definitions</th><th>${escape(c.labelA)} missed</th><th>${escape(c.labelB)} missed</th><th>Improved</th><th>Regressed</th><th>Still missed</th><th>Flag</th></tr></thead><tbody>${questionRows}</tbody></table></div><h4>Individual change summary</h4><div class="analysis-scroll"><table class="upload-results-table"><thead><tr><th>Student Name</th><th>Student ID</th><th>Incorrect → correct</th><th>Correct → incorrect</th><th>Missed both</th></tr></thead><tbody>${studentRows}</tbody></table></div><p class="hint">Student changes are matched by Student ID found in both files. Question positions are compared across the matching FAST export structure. Percent missed uses students assessed on each question or standard. ELL status is aggregate-only, and Section 504 data is ignored. Yellow rows mark questions missed by at least 45% in the second file.</p>`;
  }

  function prepareComparisonExport(c){invalidateSpreadsheet();resetPdf();state.analysis=null;state.comparison=c;$('spreadsheet-export').hidden=false;$('spreadsheet-note').textContent=`Comparison completed for ${c.matched.length} matched students. Create either report below.`;$('spreadsheet-sheets').textContent='Excel includes PM Level, Reporting Category, Standard, Question, Student Change, and 45%+ comparison worksheets. PDF includes a whole-class comparison followed by each matched student name and ID.'}
  function buildComparisonWorkbook(c){
    const dash=v=>v==null?'':v,standardHeader=['Standard Code','Description',`${c.labelA} % Above`,`${c.labelA} % At`,`${c.labelA} % Below/Missed`,`${c.labelB} % Above`,`${c.labelB} % At`,`${c.labelB} % Below/Missed`],standardData=c.standards.map(s=>[s.code,s.description,s.a?.hasStatus?s.a.above/c.first.students.length:'',s.a?.hasStatus?s.a.at/c.first.students.length:'',s.a?.pctMissed??'',s.b?.hasStatus?s.b.above/c.second.students.length:'',s.b?.hasStatus?s.b.at/c.second.students.length:'',s.b?.pctMissed??'']);
    const questionHeader=['Question','Standard Code','Description',`${c.labelA} % Missed`,`${c.labelB} % Missed`,'Percentage-Point Change','Students Improved','Students Regressed','Students Still Missed','45%+ Latest Priority'],questionData=c.questionResults.map(q=>[q.label,q.code,q.description,dash(q.aMissed),dash(q.bMissed),q.aMissed!=null&&q.bMissed!=null?q.bMissed-q.aMissed:'',q.improved.length,q.regressed.length,q.stillMissed.length,q.priority?'Yes':'No']),studentHeader=['Student Name','Student ID','Questions Improved','Questions Regressed','Questions Missed in Both'],studentData=c.students.map(s=>[s.name||'',s.code,s.improved,s.regressed,s.stillMissed]),priorityData=questionData.filter(r=>r[9]==='Yes');
    const aLevel=c.first.students.filter(s=>Number.isFinite(s.pm)),bLevel=c.second.students.filter(s=>Number.isFinite(s.pm)),levelData=[1,2,3,4,5].map(level=>[`Level ${level}`,aLevel.length?aLevel.filter(s=>s.pm===level).length/aLevel.length:'',bLevel.length?bLevel.filter(s=>s.pm===level).length/bLevel.length:'']),categoryHeader=['Reporting Category',`${c.labelA} % Above`,`${c.labelA} % At/Near`,`${c.labelA} % Below`,`${c.labelB} % Above`,`${c.labelB} % At/Near`,`${c.labelB} % Below`],categoryData=(c.categories||[]).filter(x=>x.a?.entered||x.b?.entered).map(x=>[x.label,x.a?.entered?x.a.above/x.a.entered:'',x.a?.entered?x.a.at/x.a.entered:'',x.a?.entered?x.a.below/x.a.entered:'',x.b?.entered?x.b.above/x.b.entered:'',x.b?.entered?x.b.at/x.b.entered:'',x.b?.entered?x.b.below/x.b.entered:'']);
    const wb=XLSX.utils.book_new(),levelWs=XLSX.utils.aoa_to_sheet([['PM Level',`${c.labelA} Percent`,`${c.labelB} Percent`],...levelData]),categoryWs=XLSX.utils.aoa_to_sheet([categoryHeader,...categoryData]),standardWs=XLSX.utils.aoa_to_sheet([standardHeader,...standardData]),questionWs=XLSX.utils.aoa_to_sheet([questionHeader,...questionData]),studentWs=XLSX.utils.aoa_to_sheet([studentHeader,...studentData]),priorityWs=XLSX.utils.aoa_to_sheet([questionHeader,...(priorityData.length?priorityData:[['No latest question reached the 45% threshold.']])]);
    styleSheet(standardWs,[20,55,18,16,22,18,16,22],`A1:H${standardData.length+1}`);styleSheet(questionWs,[32,20,55,18,18,24,18,18,20,20],`A1:J${questionData.length+1}`);styleSheet(studentWs,[24,20,20,24],`A1:D${studentData.length+1}`);styleSheet(priorityWs,[32,20,55,18,18,24,18,18,20,20],priorityData.length?`A1:J${priorityData.length+1}`:'');
    styleSheet(levelWs,[16,18,18],`A1:C${levelData.length+1}`);styleSheet(categoryWs,[34,18,20,18,18,20,18],`A1:G${categoryData.length+1}`);levelData.forEach((_,i)=>['B','C'].forEach(col=>{const cell=levelWs[`${col}${i+2}`];if(cell)cell.z='0.0%'}));categoryData.forEach((_,i)=>['B','C','D','E','F','G'].forEach(col=>{const cell=categoryWs[`${col}${i+2}`];if(cell)cell.z='0.0%'}));standardData.forEach((_,i)=>['C','D','E','F','G','H'].forEach(col=>{const cell=standardWs[`${col}${i+2}`];if(cell)cell.z='0.0%'}));questionData.forEach((_,i)=>['D','E','F'].forEach(col=>{const cell=questionWs[`${col}${i+2}`];if(cell)cell.z='0.0%'}));priorityData.forEach((_,i)=>['D','E','F'].forEach(col=>{const cell=priorityWs[`${col}${i+2}`];if(cell)cell.z='0.0%'}));
    XLSX.utils.book_append_sheet(wb,levelWs,'PM Level Comparison');XLSX.utils.book_append_sheet(wb,categoryWs,'Category Comparison');XLSX.utils.book_append_sheet(wb,standardWs,'Standard Comparison');XLSX.utils.book_append_sheet(wb,questionWs,'Question Comparison');XLSX.utils.book_append_sheet(wb,studentWs,'Student Changes');XLSX.utils.book_append_sheet(wb,priorityWs,'45%+ Latest Questions');const bytes=XLSX.write(wb,{bookType:'xlsx',type:'array'});if(spreadsheetUrl)URL.revokeObjectURL(spreadsheetUrl);spreadsheetUrl=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const link=$('download-spreadsheet'),date=new Date().toISOString().slice(0,10);link.href=spreadsheetUrl;link.download=`fast-pm-${c.labelA}-to-${c.labelB}-comparison-${date}.xlsx`;$('create-spreadsheet').hidden=true;$('spreadsheet-note').textContent=`Excel comparison download started for ${c.matched.length} matched students. If it did not start, use the Excel retry link below.`;startDownload(link)
  }

  let pdfUrl='';
  function resetPdf(){if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdfUrl='';const link=$('download-pdf');if(link){link.hidden=true;link.removeAttribute('href')}$('create-pdf').hidden=false}
  function pdfSafe(value){return String(value??'').normalize('NFKD').replace(/[^\x20-\x7E]/g,'-').replace(/([\\()])/g,'\\$1')}
  function wrap(value,width=92){const words=String(value??'').replace(/\s+/g,' ').trim().split(' '),lines=[];let line='';words.forEach(word=>{if(!word)return;const next=line?`${line} ${word}`:word;if(next.length>width&&line){lines.push(line);line=word}else line=next});if(line)lines.push(line);return lines.length?lines:['']}
  function makePdf(items,title){
    const pages=[];let current=[];const push=item=>{const wrapped=wrap(item.text,item.width||92);wrapped.forEach((text,i)=>{if(current.length>=50){pages.push(current);current=[]}current.push({text,bold:item.bold,size:item.size||10,gap:i===wrapped.length-1?(item.gap||0):0})})};items.forEach(push);if(current.length)pages.push(current);
    const objects=[];objects[1]='<< /Type /Catalog /Pages 2 0 R >>';objects[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';objects[4]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';const kids=[];
    pages.forEach((lines,index)=>{const pageId=5+index*2,contentId=pageId+1;kids.push(`${pageId} 0 R`);let y=756,commands='';lines.forEach(line=>{commands+=`BT /${line.bold?'F2':'F1'} ${line.size} Tf 54 ${y} Td (${pdfSafe(line.text)}) Tj ET\n`;y-=line.size+3+(line.gap||0)});commands+=`BT /F1 8 Tf 54 28 Td (${pdfSafe(`${title} - Page ${index+1} of ${pages.length}`)}) Tj ET\n`;objects[pageId]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentId} 0 R >>`;objects[contentId]=`<< /Length ${new TextEncoder().encode(commands).length} >>\nstream\n${commands}endstream`});objects[2]=`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${pages.length} >>`;
    let pdf='%PDF-1.4\n',offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=new TextEncoder().encode(pdf).length;pdf+=`${i} 0 obj\n${objects[i]}\nendobj\n`}const xref=new TextEncoder().encode(pdf).length;pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)pdf+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new TextEncoder().encode(pdf)
  }
  function analysisPdfItems(a){
    const items=[{text:'FAST PM Teacher Report',bold:true,size:20,gap:8},{text:`Source: ${a.filename}`,size:9,gap:8},{text:'Whole-Class Summary',bold:true,size:14,gap:4},{text:`The file contains ${a.students.length} students, ${a.benchmarks.length} standards, and ${a.questions.length} numbered questions. ${a.questionPriority.length} questions were missed by at least 45% of assessed students.`,gap:5}];
    const valid=a.students.filter(s=>Number.isFinite(s.pm));if(valid.length)items.push({text:`Achievement levels: ${[1,2,3,4,5].map(level=>`Level ${level}: ${pct(valid.filter(s=>s.pm===level).length/valid.length)}`).join(' | ')}`,gap:5});
    (a.categorySummary||[]).filter(c=>c.entered).forEach(c=>items.push({text:`${c.label}: ${pct(c.above/c.entered)} above, ${pct(c.at/c.entered)} at/near, ${pct(c.below/c.entered)} below (${c.entered} reported).`}));
    if(a.ellSummary?.available){const e=a.ellSummary;items.push({text:'ELL Quantitative Summary (Aggregate Only)',bold:true,size:13,gap:3},{text:`ELL: ${e.ellCount} of ${e.reported} students (${pct(e.ellPercent)}). Non-ELL: ${e.nonEllCount}. Individual student ELL labels are not included.`,gap:3});e.ell.categories.forEach((c,i)=>{const n=e.nonEll.categories[i],rate=(x,k)=>x.entered?pct(x[k]/x.entered):'not reported';items.push({text:`${c.name} below standard - ELL: ${rate(c,'below')}; non-ELL: ${rate(n,'below')}.`})})}
    items.push({text:'Priority Standards and Questions',bold:true,size:14,gap:4});a.priority.forEach(b=>items.push({text:`${b.code} - ${pct(b.pctMissed)} missed. ${b.description}`,gap:2}));a.questionPriority.forEach(q=>items.push({text:`${q.label}: ${pct(q.pctMissed)} missed - ${q.code}. ${q.description}`,gap:2}));
    items.push({text:'Individual Student Breakdown',bold:true,size:14,gap:4},{text:'Student names and IDs are shown for teacher use. Individual ELL labels and Section 504 information are not displayed.',size:9,gap:5});a.students.forEach(s=>{const missed=Object.entries(s.items).filter(([,v])=>v==='incorrect').map(([code])=>code),correct=Object.entries(s.items).filter(([,v])=>v==='correct').length,cats=Object.entries(s.categoryPerformance).map(([k,v])=>`${k}: ${v}`).join(', ');items.push({text:`${s.name||'Student'} — ${s.code}`,bold:true,size:11,gap:1},{text:`PM level: ${s.pm||'not reported'} | Standards correct: ${correct} | Standards missed: ${missed.length}${cats?` | Categories: ${cats}`:''}`},{text:`Missed standards: ${missed.join(', ')||'None recorded'}`,gap:4})});items.push({text:'Method and Privacy Note',bold:true,size:12,gap:2},{text:'Percent missed uses students assessed on each question or standard. A standard is counted as missed when at least one aligned item was missed. This report supports instructional planning and should be verified against the original FAST report. ELL is shown only in aggregate; Section 504 data is not used.'});return items
  }
  function comparisonPdfItems(c){const items=[{text:`FAST PM Comparison: ${c.labelA} to ${c.labelB}`,bold:true,size:20,gap:8},{text:'Whole-Class Summary',bold:true,size:14,gap:4},{text:`Matched students: ${c.matched.length}. Unmatched records: ${c.onlyA+c.onlyB}. Latest questions at or above the 45% missed threshold: ${c.priority.length}.`,gap:5}];[c.first,c.second].forEach((a,i)=>{const e=a.ellSummary;items.push({text:`${i?c.labelB:c.labelA}: ${a.students.length} students${e?.available?`; ELL ${e.ellCount} of ${e.reported} (${pct(e.ellPercent)})`:''}.`,gap:2})});items.push({text:'Priority Question Changes',bold:true,size:14,gap:4});c.questionResults.forEach(q=>items.push({text:`${q.label} - ${q.code}: ${c.labelA} ${q.aMissed==null?'not reported':pct(q.aMissed)} missed; ${c.labelB} ${q.bMissed==null?'not reported':pct(q.bMissed)} missed. Improved ${q.improved.length}; regressed ${q.regressed.length}; missed both ${q.stillMissed.length}${q.priority?' [45%+ PRIORITY]':''}.`,gap:2}));items.push({text:'Individual Student Breakdown',bold:true,size:14,gap:4});c.students.forEach(s=>items.push({text:`${s.name||'Student'} — ${s.code}: ${s.improved} questions improved, ${s.regressed} regressed, ${s.stillMissed} missed in both.`,gap:2}));items.push({text:'Privacy Note',bold:true,size:12,gap:2},{text:'Student names and IDs are shown for teacher use. Individual ELL labels and Section 504 information are not displayed. ELL results are class-level aggregates only.'});return items}
  function buildPdf(){const comparison=state.comparison,analysis=state.analysis;if(!comparison&&!analysis)return;const title=comparison?`FAST PM ${comparison.labelA} to ${comparison.labelB} Comparison`:'FAST PM Teacher Report',bytes=makePdf(comparison?comparisonPdfItems(comparison):analysisPdfItems(analysis),title);if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdfUrl=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));const link=$('download-pdf'),date=new Date().toISOString().slice(0,10);link.href=pdfUrl;link.download=comparison?`fast-pm-${comparison.labelA}-to-${comparison.labelB}-report-${date}.pdf`:`fast-pm-teacher-report-${date}.pdf`;$('create-pdf').hidden=true;$('spreadsheet-note').textContent='PDF download started. If it did not start, use the PDF retry link below.';startDownload(link)}

  $('fast-upload').addEventListener('change',event=>{const file=event.target.files[0];state.file=file||null;state.analysis=null;state.comparison=null;$('analyze-upload').disabled=!file;invalidateSpreadsheet();if(!file){setStatus('No file selected. Maximum file size: 10 MB.');return}setStatus(`${file.name} selected. Press Analyze This PM Data.`,'ready')});
  $('analyze-upload').addEventListener('click',async()=>{if(!state.file)return;$('analyze-upload').disabled=true;setStatus('Reading and analyzing the first worksheet…');try{const analysis=await readUpload(state.file);renderAnalysis(analysis);prepareUploadExport(analysis);const notes=[`${analysis.students.length} students`,`${analysis.benchmarks.length} standards`,`${analysis.questions.length} questions`,`${analysis.questionPriority.length} questions at 45%+`];if(analysis.ellSummary?.available)notes.push(`${pct(analysis.ellSummary.ellPercent)} ELL`);if(analysis.unreadable)notes.push(`${analysis.unreadable} unrecognized cells treated as missing`);setStatus(`Analysis ready: ${notes.join(' • ')}.`,'ready');$('analysis-box').scrollIntoView({behavior:'smooth',block:'nearest'})}catch(error){state.analysis=null;setStatus(error.message||'The file could not be analyzed.','error');$('analysis-box').innerHTML=`<h3>Upload needs attention</h3><p>${escape(error.message||'The file could not be analyzed.')}</p>`}finally{$('analyze-upload').disabled=false}});
  function compareReady(){const ready=!!state.compareFiles.a&&!!state.compareFiles.b;$('analyze-compare').disabled=!ready;return ready}
  ['a','b'].forEach(key=>{$(`compare-upload-${key}`).addEventListener('change',event=>{const file=event.target.files[0]||null;state.compareFiles[key]=file;state.comparison=null;invalidateSpreadsheet();compareReady();const names=[state.compareFiles.a?.name,state.compareFiles.b?.name].filter(Boolean);$('compare-status').className='upload-status ready';$('compare-status').textContent=names.length===2?`${names.join(' and ')} selected. Press Compare Both PM Files.`:`${names[0]||'One file'} selected. Choose the other CSV file.`})});
  $('analyze-compare').addEventListener('click',async()=>{if(!compareReady())return;const labelA=$('compare-label-a').value,labelB=$('compare-label-b').value;if(labelA===labelB){$('compare-status').className='upload-status error';$('compare-status').textContent='Choose two different PM labels before comparing.';return}$('analyze-compare').disabled=true;$('compare-status').className='upload-status';$('compare-status').textContent='Reading and comparing both CSV files…';try{const[first,second]=await Promise.all([readUpload(state.compareFiles.a),readUpload(state.compareFiles.b)]),comparison=compareAnalyses(first,second,labelA,labelB);renderComparison(comparison);prepareComparisonExport(comparison);$('compare-status').className='upload-status ready';$('compare-status').textContent=`Comparison ready: ${comparison.matched.length} matched students • ${comparison.questionResults.length} questions • ${comparison.priority.length} latest questions at 45%+.`;$('analysis-box').scrollIntoView({behavior:'smooth',block:'nearest'})}catch(error){state.comparison=null;$('compare-status').className='upload-status error';$('compare-status').textContent=error.message||'The files could not be compared.';$('analysis-box').innerHTML=`<h3>Comparison needs attention</h3><p>${escape(error.message||'The files could not be compared.')}</p>`}finally{compareReady()}});
  $('create-spreadsheet').addEventListener('click',()=>{if(state.comparison)buildComparisonWorkbook(state.comparison);else if(state.analysis)buildUploadWorkbook(state.analysis)});
  $('create-pdf').addEventListener('click',buildPdf);
  $('clear-fast-data').addEventListener('click',()=>{state.file=null;state.analysis=null;state.comparison=null;state.compareFiles={a:null,b:null};['fast-upload','compare-upload-a','compare-upload-b'].forEach(id=>{const input=$(id);if(input)input.value=''});$('analyze-upload').disabled=true;$('analyze-compare').disabled=true;invalidateSpreadsheet();resetPdf();$('analysis-box').innerHTML='<h3 style="margin-top:0">Analysis will appear here</h3><p>Upload one file above, or choose two CSV files to compare.</p>';$('upload-status').className='upload-status';$('upload-status').textContent='No file selected. Maximum file size: 10 MB.';$('compare-status').className='upload-status';$('compare-status').textContent='Choose both CSV files to compare.';window.scrollTo({top:$('data-panel').offsetTop-90,behavior:'smooth'})});
})();
